"use strict";

const MISSING_TOKEN = "MISSING_TOKEN";
const INVALID_TOKEN = "INVALID_TOKEN";
const BAD_TOKEN = "BAD_TOKEN";
const FIRST_POST_NOT_ALLOWED = "FIRST_POST_NOT_ALLOWED";

module.exports = {
  MISSING_TOKEN,
  INVALID_TOKEN,
  BAD_TOKEN,
  FIRST_POST_NOT_ALLOWED
};
